'use strict';
/**
 * Makes the `raven` command work from any terminal and keeps it working.
 *
 *   install()    writes a launcher and puts its folder on the PATH
 *   autoHeal()   quick check at startup; silently repairs a missing/stale
 *                launcher or a PATH entry that disappeared (folder moved,
 *                shell profile reset...)
 *   uninstall()  removes everything and disables auto-repair
 *
 * macOS / Linux : ~/.local/bin/raven  + a marked block in the shell profiles
 * Windows       : %USERPROFILE%\.raven\bin\raven.cmd + the user PATH variable
 *
 * Every function takes an optional `ctx` so it can be tested against a
 * temporary HOME without touching the real machine.
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const MARK_START = '# >>> raven >>>';
const MARK_END = '# <<< raven <<<';
const RECHECK_MS = 24 * 60 * 60 * 1000;

function makeCtx(overrides = {}) {
  return {
    platform: process.platform,
    home: os.homedir(),
    env: process.env,
    nodePath: process.execPath,
    installDir: path.resolve(__dirname, '..'),
    skipWindowsRegistry: false, // tests
    ...overrides,
  };
}

const isWin = (c) => c.platform === 'win32';
const binDir = (c) => (isWin(c) ? path.join(c.home, '.raven', 'bin') : path.join(c.home, '.local', 'bin'));
const launcherPath = (c) => path.join(binDir(c), isWin(c) ? 'raven.cmd' : 'raven');
const entryPoint = (c) => path.join(c.installDir, 'bin', 'raven.js');
const statePath = (c) => path.join(c.home, '.raven', 'setup.json');

// ---------------------------------------------------------------------------
// Launcher
// ---------------------------------------------------------------------------

function launcherContent(c) {
  const entry = entryPoint(c);
  if (isWin(c)) {
    return [
      '@echo off',
      'rem Raven launcher - generated by `raven setup` (safe to delete)',
      'setlocal',
      'set "RAVEN_NODE=node"',
      `where node >nul 2>nul || set "RAVEN_NODE=${c.nodePath}"`,
      `"%RAVEN_NODE%" "${entry}" %*`,
      'exit /b %ERRORLEVEL%',
      '',
    ].join('\r\n');
  }
  const q = (s) => `'${String(s).replace(/'/g, `'\\''`)}'`;
  return [
    '#!/bin/sh',
    '# Raven launcher - generated by `raven setup` (safe to delete)',
    `NODE="$(command -v node 2>/dev/null || echo ${q(c.nodePath)})"`,
    `exec "$NODE" ${q(entry)} "$@"`,
    '',
  ].join('\n');
}

function launcherState(c) {
  const file = launcherPath(c);
  if (!fs.existsSync(file)) return 'missing';
  try {
    return fs.readFileSync(file, 'utf8').includes(entryPoint(c)) ? 'ok' : 'stale';
  } catch (e) {
    return 'stale';
  }
}

/** Remove an older Raven launcher from another PATH directory. */
function removeConflictingLaunchers(c) {
  const sep = isWin(c) ? ';' : ':';
  const current = normalize(c, binDir(c));
  const removed = [];
  const seen = new Set();
  const names = isWin(c) ? ['raven.cmd', 'raven.bat', 'raven.ps1', 'raven.exe'] : ['raven'];
  for (const rawDir of String(c.env.PATH || c.env.Path || '').split(sep).filter(Boolean)) {
    let dir;
    try { dir = path.resolve(rawDir); } catch (e) { continue; }
    if (normalize(c, dir) === current || seen.has(normalize(c, dir))) continue;
    seen.add(normalize(c, dir));
    for (const name of names) {
      const candidate = path.join(dir, name);
      try {
        if (!fs.existsSync(candidate) || !fs.statSync(candidate).isFile()) continue;
        if (!fs.readFileSync(candidate, 'utf8').includes('Raven launcher - generated by')) continue;
        fs.unlinkSync(candidate);
        removed.push(candidate);
      } catch (e) {
        // PATH can contain protected system directories; keep installing.
      }
    }
  }
  return removed;
}

/** Reset the generated project-local state requested by the installer. */
function resetProjectState(c) {
  c = makeCtx(c);
  const root = path.join(c.installDir, '.raven');
  fs.mkdirSync(path.join(root, 'commands'), { recursive: true });
  return root;
}

function writeLauncher(c) {
  fs.mkdirSync(binDir(c), { recursive: true });
  const file = launcherPath(c);
  fs.writeFileSync(file, launcherContent(c), { mode: 0o755 });
  if (!isWin(c)) fs.chmodSync(file, 0o755);
  return file;
}

// ---------------------------------------------------------------------------
// PATH handling
// ---------------------------------------------------------------------------

function normalize(c, p) {
  const s = path.resolve(String(p).replace(/[\\/]+$/, '') || '/');
  return isWin(c) ? s.toLowerCase() : s;
}

function onCurrentPath(c) {
  const sep = isWin(c) ? ';' : ':';
  const target = normalize(c, binDir(c));
  return String(c.env.PATH || c.env.Path || '')
    .split(sep)
    .filter(Boolean)
    .some((p) => normalize(c, p) === target);
}

/** Shell profiles to update (posix). The detected shell's file is created if missing. */
function profileFiles(c) {
  const h = c.home;
  const shell = path.basename(String(c.env.SHELL || ''));
  const files = [];
  const add = (f, create) => {
    if (!files.includes(f) && (create || fs.existsSync(f))) files.push(f);
  };
  if (shell === 'fish') add(path.join(h, '.config', 'fish', 'config.fish'), true);
  if (shell === 'zsh' || c.platform === 'darwin') add(path.join(h, '.zshrc'), true);
  if (shell === 'bash' || shell === '' || shell === 'sh') add(path.join(h, '.bashrc'), shell === 'bash');
  for (const f of ['.zshrc', '.bashrc', '.bash_profile', '.profile']) add(path.join(h, f), false);
  if (!files.length) add(path.join(h, '.profile'), true);
  return files;
}

function profileBlock(file) {
  if (file.endsWith('config.fish')) {
    return `${MARK_START}\nfish_add_path -g "$HOME/.local/bin"\n${MARK_END}\n`;
  }
  return `${MARK_START}\ncase ":$PATH:" in *":$HOME/.local/bin:"*) ;; *) export PATH="$HOME/.local/bin:$PATH" ;; esac\n${MARK_END}\n`;
}

function hasBlock(file) {
  try {
    return fs.readFileSync(file, 'utf8').includes(MARK_START);
  } catch (e) {
    return false;
  }
}

function addBlock(file) {
  if (hasBlock(file)) return false;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  let current = '';
  try {
    current = fs.readFileSync(file, 'utf8');
  } catch (e) {
    /* new file */
  }
  const sep = current && !current.endsWith('\n') ? '\n\n' : current ? '\n' : '';
  fs.writeFileSync(file, `${current}${sep}${profileBlock(file)}`);
  return true;
}

function removeBlock(file) {
  let text;
  try {
    text = fs.readFileSync(file, 'utf8');
  } catch (e) {
    return false;
  }
  const rx = new RegExp(`\\n?${MARK_START}[\\s\\S]*?${MARK_END}\\n?`, 'g');
  if (!rx.test(text)) return false;
  fs.writeFileSync(file, text.replace(rx, '\n').replace(/\n{3,}/g, '\n\n'));
  return true;
}

/** PowerShell snippet that adds/removes the bin dir in the *user* PATH. */
function windowsPathScript(add) {
  return [
    "$d = $env:RAVEN_BIN_DIR.TrimEnd('\\')",
    "$cur = [Environment]::GetEnvironmentVariable('Path', 'User')",
    "$parts = @(); if ($cur) { $parts = $cur -split ';' | Where-Object { $_ -ne '' } }",
    "$has = $parts | Where-Object { $_.TrimEnd('\\') -ieq $d }",
    add
      ? "if (-not $has) { [Environment]::SetEnvironmentVariable('Path', (($parts + $d) -join ';'), 'User'); Write-Output 'added' } else { Write-Output 'present' }"
      : "if ($has) { [Environment]::SetEnvironmentVariable('Path', (($parts | Where-Object { $_.TrimEnd('\\') -ine $d }) -join ';'), 'User'); Write-Output 'removed' } else { Write-Output 'absent' }",
  ].join('; ');
}

function windowsUserPath(c, add) {
  if (c.skipWindowsRegistry) return 'skipped';
  const r = spawnSync('powershell', ['-NoProfile', '-NonInteractive', '-Command', windowsPathScript(add)], {
    env: { ...c.env, RAVEN_BIN_DIR: binDir(c) },
    encoding: 'utf8',
    timeout: 20000,
  });
  if (r.error || r.status !== 0) throw new Error(`could not update the Windows PATH (${(r.error && r.error.message) || r.stderr || r.status})`);
  return String(r.stdout).trim();
}

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

function readState(c) {
  try {
    return JSON.parse(fs.readFileSync(statePath(c), 'utf8'));
  } catch (e) {
    return {};
  }
}

function writeState(c, patch) {
  try {
    fs.mkdirSync(path.dirname(statePath(c)), { recursive: true });
    fs.writeFileSync(statePath(c), JSON.stringify({ ...readState(c), ...patch }, null, 2));
  } catch (e) {
    /* state is best-effort */
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Where does the PATH entry live (or not)? */
function persistedState(c) {
  if (isWin(c)) return onCurrentPath(c) ? 'yes' : 'unknown';
  if (onCurrentPath(c)) return 'yes';
  return profileFiles(c).some(hasBlock) ? 'profile' : 'no';
}

/** Read-only health check. */
function check(ctx) {
  const c = makeCtx(ctx);
  const launcher = launcherState(c);
  const persisted = persistedState(c);
  const problems = [];
  if (launcher === 'missing') problems.push('launcher missing');
  if (launcher === 'stale') problems.push('launcher points to another folder');
  if (persisted === 'no') problems.push(`${binDir(c)} is not on your PATH`);
  return {
    ok: problems.length === 0,
    problems,
    launcher,
    launcherFile: launcherPath(c),
    binDir: binDir(c),
    onCurrentPath: onCurrentPath(c),
    persisted,
    needsNewTerminal: !onCurrentPath(c),
  };
}

/** Create/repair the launcher and the PATH entry. Idempotent. */
function install(ctx, opts = {}) {
  const c = makeCtx(ctx);
  const changes = [];

  if (opts.resetProject === true) {
    const projectState = resetProjectState(c);
    changes.push(`project state reset: ${projectState}`);
  }

  for (const old of removeConflictingLaunchers(c)) changes.push(`old launcher removed: ${old}`);

  if (launcherState(c) !== 'ok') {
    changes.push(`launcher written: ${writeLauncher(c)}`);
  }

  if (!onCurrentPath(c)) {
    if (isWin(c)) {
      const r = windowsUserPath(c, true);
      if (r === 'added') changes.push('added to your user PATH');
    } else {
      for (const f of profileFiles(c)) {
        if (addBlock(f)) changes.push(`PATH line added to ${f.replace(c.home, '~')}`);
      }
    }
  }

  writeState(c, { disabled: false, installDir: c.installDir, binDir: binDir(c), checkedAt: Date.now(), version: 1 });
  return { changes, needsNewTerminal: !onCurrentPath(c), launcherFile: launcherPath(c), binDir: binDir(c) };
}

/**
 * Cheap startup check (called on every `raven` launch). Repairs only when
 * something is actually broken, and never more than a verification per day.
 */
function autoHeal(ctx) {
  const c = makeCtx(ctx);
  const env = c.env;
  if (env.RAVEN_NO_AUTOINSTALL || env.CI) return { skipped: 'disabled by environment' };
  if (c.installDir.split(path.sep).includes('node_modules')) return { skipped: 'managed by npm' };
  const state = readState(c);
  if (state.disabled) return { skipped: 'uninstalled by user' };

  const launcher = launcherState(c);
  const fresh = state.installDir === c.installDir && Date.now() - (state.checkedAt || 0) < RECHECK_MS;
  if (launcher === 'ok' && (onCurrentPath(c) || fresh)) return { skipped: 'healthy' };

  try {
    const result = install(c, { resetProject: false });
    return { repaired: result.changes.length > 0, ...result };
  } catch (e) {
    return { error: e.message };
  }
}

function uninstall(ctx) {
  const c = makeCtx(ctx);
  const removed = [];
  const file = launcherPath(c);
  if (fs.existsSync(file)) {
    fs.unlinkSync(file);
    removed.push(`launcher removed: ${file}`);
  }
  if (isWin(c)) {
    try {
      if (windowsUserPath(c, false) === 'removed') removed.push('removed from your user PATH');
    } catch (e) {
      removed.push(`(could not edit the Windows PATH: ${e.message})`);
    }
  } else {
    for (const f of ['.zshrc', '.bashrc', '.bash_profile', '.profile'].map((n) => path.join(c.home, n)).concat(path.join(c.home, '.config', 'fish', 'config.fish'))) {
      if (removeBlock(f)) removed.push(`PATH line removed from ${f.replace(c.home, '~')}`);
    }
  }
  writeState(c, { disabled: true, checkedAt: Date.now() });
  return { removed };
}

module.exports = { install, check, autoHeal, uninstall, makeCtx, launcherContent, windowsPathScript, profileBlock, resetProjectState, removeConflictingLaunchers, MARK_START, MARK_END };
